### ISSUE TITLE
Does Not Seem to Load after Installation

### ISSUE THREAD

**Issue by Kittster** [roblenvic/Bonanza-Turbo#3]
Hi, I am looking forward to this Mod as I am about to fly around the world again.  Last time was in XPlane (Earhart's Route) and this time in MSFS (Sightseeing tour).  I like the G36 best of the planes I've tried in the default version.  The Turbos are too fast and the G36 has a great view out the windows, plus I enjoy leaning the engines.  I only wished it would go faster and now you guys have done it.  Except it does not seem to work on my machine.  

I found your Mod from the "Clumsy Mods" website.  They had a note in it that it is not compatible with G36 fixes.  So I removed the z-bonanza-g36-improvement-project from my Community folder, but still it did not seem to load.  At least I cannot see the additional liveries that look very nice.

Below is a picture of what is in my Community Folder.  Perhaps one of these needs to be removed for this to work properly.  Any feedback you can provide would be most grateful.

![Community Folder](https://user-images.githubusercontent.com/67450576/97092959-c1fe8180-160d-11eb-856f-9327530ebe52.png)

Thanks - Kitt Prible (Kittster)

Clumsy Website:
https://docs.google.com/spreadsheets/u/2/d/1QON0otZ4WYEX-tF_xKmdSN9WiahIgZThFPOgFbQYN6E/htmlview?gid=1919779397

**Comment by roblenvic** [comment]
Hi Kit,

It looks like you have a lot of other mods also for the Bonanza. Just for
the time being, remove all the other Bonanza related mods and put them in a
safe place. The only exception is the working title G1000 mod which works
fine with my mod. You can combine my mod (or any mod) with other liveries
but you have to edit your layout.json file (only 1 of those files per mod).
You cannot run the Turbo mod because it has its own unique manifest and
layout.

You can combine other liveries and there is a tool you can use which
creates a layout file for you without you having to waste time editing.
Here is the link to the tool:

https://github.com/HughesMDflyer4/MSFSLayoutGenerator

Kind Regards,

Robert

**Comment by Kittster** [comment]
Thank you Robert for this explanation.  I got the liveries to change w/o issue after following  your suggestions.  I first removed all the items in my Community and then added the G36 Liveries back one at a time while running the layout.json file through the generator.  That seemed to do the trick and all the liveries are back including yours so that all seems well - Thank you.

I am not sure what you mean by:  *_**You cannot run the Turbo mod because it has its own unique manifest and
layout.**_*

If that is true, then how do I get the Manifest file and layout for the Turbo Mod to get it to go 40 Knots faster?  That part is confusing to me.  Maybe I missed something in the documentation.  Please help me.  The liveries are nice, but I have the need for speed to circumvent the world once again.

Blessings - Kitt Prible

**Comment by roblenvic** [comment]
I'm pleased you got the extra liveries to work. What I meant was that you
could not (in the past) run it before because of the layout file, but you
clearly have found the solution which is great! Sorry I should not
have mentioned the manifest, It's not an issue.

**Comment by Kittster** [comment]
Thank you Robert for this explanation.  I got the liveries to change w/o issue after following  your suggestions.  I first removed all the items in my Community and then added the G36 Liveries back one at a time while running the layout.json file through the generator.  That seemed to do the trick and all the liveries are back including yours so that all seems well - Thank you.

I am not sure what you mean by:  *_You cannot run the Turbo mod because it has its own unique manifest and
layout._*

If that is true, then how do I get the Manifest file and layout for the Turbo Mod to get it to go 40 Knots faster?  That part is confusing to me.  Maybe I missed something in the documentation.  Please help me.  The liveries are nice, but I have the need for speed to circumvent the world once again.

Blessings - Kitt Prible

**Comment by Kittster** [comment]
Thank you Robert for explaining the Manifest file and that it was something left over from the past.  I think it is all working, I'll take it up higher as I was just doing short tests with it yesterday and I think I will get the benefit of the Turbo speed.  If not, I'll let you know.

Meanwhile - that MSFSLayoutGenerator exe is a slick program.  I'm glad it was as easy as drag and drop.  I'm a retired Oracle SQL Developer and was hoping to not have to go back into coding again in retirement.  Its time to enjoy life and let the young bucks do the heavy work for a change.

Blessings again - Kitt Prible
