### ISSUE TITLE
Thanks and the Bonanza Performance Improvement Project

### ISSUE THREAD

**Issue by KevyKevTPA** [roblenvic/Bonanza-Turbo#9]
First, I want to say thanks, whenever I fly the Bonanza, I'm flying the turbo version, unless I'm trying to get some achievement that doesn't allow it.

Are there any plans to make this compatible with the Bonanza Performance Project, or even better, to merge them together?

Thanks,
KKT

**Comment by roblenvic** [comment]
Hi Kevin,

I'm glad you are enjoying the Turbo Bonanza. There are no plans to merge
the two mods as although both mods have their strengths I wish to keep
control of my own mod for personal reasons.

Kind Regards,

Robert

**Comment by KevyKevTPA** [comment]
I get that.  I would probably have the same feelings about it had I been the one that made what you made!  How about at least making them compatible with each other?

**Comment by roblenvic** [comment]
Well, they have quite a different approach and I don't think we would agree
for example on the flight model and other aspects. Of course co-operation
is sometimes a good thing (for example the FBW A320 project which with its
complexity requires a whole team with different skills). The Bonanza is a
more simple aircraft that one or a couple of people with experience can
mod. Also the Turbo version is quite different from the normally aspirated
version and qualifies as an entirely different aircraft.

**Comment by KevyKevTPA** [comment]
Gotcha.  I actually learned something new today.  Thanks for your time on this question, and thanks for creating what you did.  Like I said, if I'm flying a Bonanza, it's the turbo version one!
